name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: prepare-lua
      run: |
        sudo apt-get install libreadline-dev -y
        sudo wget https://www.lua.org/ftp/lua-5.3.4.tar.gz
        sudo tar -xf lua-5.3.4.tar.gz
        cd lua-5.3.4
        sudo make linux
        sudo make install
        
    - name: build
      run: |
        cmake .
        make
        ./blua
